teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 3.0

    axis_angular:
      yaw: 0  # only left stick = 0, left and right = 3
    scale_angular:
      yaw: 0.7

    enable_button: 4  # L1 shoulder button
    enable_turbo_button: 5  # R1 shoulder button
